Add integration for QtQuick Controls 2 applications
FedoraQt/QGnomePlatform pull request #130
Opened 2023-03-05 01:10 UTC by JBBgameich

This is untested, but should work

2023-03-05 08:39 UTC, grulja commented
I think the dependency on qqc2-desktop-style should be runtime and optional, because we don't want to automatically bring KDE Frameworks into GNOME. There should be some runtime check if qqc2-desktop-style is available and use it in such case. I would then expect to use something like `Recommends: qqc2-desktop-style` in Fedora packaging where we can suggest this as an optional dependency.

2023-03-05 12:30 UTC, JBBgameich commented
I now changed it to only setting the style when it is available.
Personally I disagree with the prioritization of avoiding KF5, since applications are really broken without the style, and it has a really small dependency tree.
```
qml-module-org-kde-qqc2desktopstyle
  Depends: qml-module-org-kde-kirigami2
  Depends: qml-module-org-kde-sonnet
  Depends: qml-module-qtgraphicaleffects
  Depends: qml-module-qtqml-models2
  Depends: qml-module-qtquick-controls2
  Depends: qml-module-qtquick-layouts
  Depends: qml-module-qtquick-templates2
  Depends: qml-module-qtquick-window2
  Depends: qml-module-qtquick2
  Depends: libc6
  Depends: libkf5configcore5
  Depends: libkf5configwidgets5
  Depends: libkf5iconthemes5
  Depends: libkf5kirigami2-5
  Depends: libqt5core5a
  Depends: libqt5dbus5
 |Depends: libqt5gui5
  Depends: libqt5gui5-gles
  Depends: libqt5qml5
 |Depends: libqt5quick5
  Depends: libqt5quick5-gles
  Depends: libqt5widgets5
  Depends: libstdc++6
```

My motivation for doing this was https://mastodon.social/@tbernard/109897404484985777 btw, this is also a good example for how things look without the desktop style.

2023-03-06 07:23 UTC, grulja requested changes

2023-03-06 07:23 UTC, grulja commented on src/common/gnomesettings.h
> +Q_DECLARE_LOGGING_CATEGORY(QGnomePlatform);
This should be something like what we use in `common/`:
e.g. `Q_LOGGING_CATEGORY(QGnomePlatformTheme, "qt.qpa.qgnomeplatform.theme")`

2023-03-06 07:24 UTC, grulja commented
Btw. it also doesn't build with Qt6.

2023-03-22 17:24 UTC, JBBgameich commented
Should be all fixed now :)

2023-03-23 07:29 UTC, grulja requested changes
Looks good to me. Just fix the include and it's good to go. Thank you.

2023-03-23 07:29 UTC, grulja commented on src/theme/qgnomeplatformtheme.cpp
> +#include <QDebug>
Include QLoggingCategory instead.

2023-03-23 07:32 UTC, grulja commented on src/theme/qgnomeplatformtheme.cpp
> +#include <QDebug>
This will also fix the failing build.

2023-03-24 08:25 UTC, grulja approved these changes

2023-03-24 08:25 UTC, merged